"""
Pure (de)serialization between SherlockSettings and plain JSON-friendly dicts.

The GUI tab (C3) and later scan paths (C4/C5) persist Sherlock settings as a
single top-level config-store module. This module owns only the dict <-> object
mapping; it performs no file, DB, or config I/O so the Sherlock package stays
pure (see test_sherlock_purity). Built-ins are code-defined and regenerated by
builtin_patterns(); persistence stores only which built-ins are disabled plus
full custom-pattern rows, never a frozen copy of the built-in catalog.
"""

from __future__ import annotations

from typing import Any, Dict, List

from .model import (
    DEFAULT_COLORS,
    Severity,
    SherlockPattern,
    SherlockSettings,
    builtin_patterns,
    default_settings,
    is_valid_color,
)

# Top-level config-store module key. Must match an entry in
# shared.config_store.EXPERIMENTAL_MODULES so settings land in their own shard.
SHERLOCK_SETTINGS_KEY = "sherlock"

# Stable lowercase tokens for severities (SPEC "Severity Defaults" table).
_SEVERITY_TO_STR: Dict[Severity, str] = {
    Severity.HIGH: "high",
    Severity.MED: "med",
    Severity.LOW: "low",
}
_STR_TO_SEVERITY: Dict[str, Severity] = {v: k for k, v in _SEVERITY_TO_STR.items()}


def severity_to_str(severity: Severity) -> str:
    """Return the stable lowercase token for a severity."""
    return _SEVERITY_TO_STR[severity]


def severity_from_str(value: object, default: Severity = Severity.MED) -> Severity:
    """Map a stored token back to a Severity, falling back to *default*."""
    if isinstance(value, str):
        return _STR_TO_SEVERITY.get(value.strip().lower(), default)
    return default


def _coerce_bool(value: object, default: bool) -> bool:
    """Best-effort bool coercion for persisted values."""
    if isinstance(value, bool):
        return value
    if value is None:
        return default
    if isinstance(value, (int, float)):
        return bool(value)
    if isinstance(value, str):
        token = value.strip().lower()
        if token in ("1", "true", "yes", "on"):
            return True
        if token in ("0", "false", "no", "off", ""):
            return False
    return default


def settings_to_dict(settings: SherlockSettings) -> Dict[str, Any]:
    """Serialize SherlockSettings to a JSON-friendly dict.

    Built-ins are reduced to the list of currently-disabled keys; custom patterns
    are emitted in full.
    """
    builtin_disabled: List[str] = [
        p.key for p in settings.patterns if p.builtin and not p.enabled
    ]
    custom_patterns: List[Dict[str, Any]] = [
        {
            "key": p.key,
            "category": p.category,
            "label": p.label,
            "pattern": p.pattern,
            "severity": severity_to_str(p.severity),
            "enabled": bool(p.enabled),
        }
        for p in settings.patterns
        if not p.builtin
    ]
    colors = {
        severity_to_str(sev): settings.color_for(sev)
        for sev in (Severity.HIGH, Severity.MED, Severity.LOW)
    }
    return {
        "ignore_case": bool(settings.ignore_case),
        "run_after_probe": bool(settings.run_after_probe),
        "colors": colors,
        "builtin_disabled": builtin_disabled,
        "custom_patterns": custom_patterns,
    }


def _colors_from_dict(raw: object) -> Dict[Severity, str]:
    """Build a severity->color map, validating and defaulting per severity."""
    source = raw if isinstance(raw, dict) else {}
    colors: Dict[Severity, str] = {}
    for sev in (Severity.HIGH, Severity.MED, Severity.LOW):
        candidate = source.get(severity_to_str(sev))
        colors[sev] = candidate if is_valid_color(candidate) else DEFAULT_COLORS[sev]
    return colors


def _custom_patterns_from_list(raw: object) -> List[SherlockPattern]:
    """Build custom SherlockPattern objects, dropping malformed/empty rows."""
    if not isinstance(raw, list):
        return []
    patterns: List[SherlockPattern] = []
    for item in raw:
        if not isinstance(item, dict):
            continue
        pattern_text = item.get("pattern")
        if not isinstance(pattern_text, str) or not pattern_text.strip():
            continue
        key = item.get("key")
        if not isinstance(key, str) or not key.strip():
            continue
        patterns.append(
            SherlockPattern(
                key=key,
                category=str(item.get("category", "Custom")),
                label=str(item.get("label", "")),
                pattern=pattern_text,
                severity=severity_from_str(item.get("severity")),
                enabled=_coerce_bool(item.get("enabled", True), True),
                builtin=False,
            )
        )
    return patterns


def settings_from_dict(data: object) -> SherlockSettings:
    """Rebuild SherlockSettings from a stored dict, degrading safely.

    Missing/empty/garbage input yields default_settings(). Built-ins are
    regenerated from the current catalog and disabled per *builtin_disabled*;
    unknown disabled keys are ignored so catalog changes stay compatible.
    """
    if not isinstance(data, dict) or not data:
        return default_settings()

    disabled_raw = data.get("builtin_disabled")
    disabled_keys = {
        key for key in disabled_raw if isinstance(key, str)
    } if isinstance(disabled_raw, list) else set()

    patterns: List[SherlockPattern] = []
    for builtin in builtin_patterns():
        if builtin.key in disabled_keys:
            patterns.append(dataclass_disabled(builtin))
        else:
            patterns.append(builtin)
    patterns.extend(_custom_patterns_from_list(data.get("custom_patterns")))

    return SherlockSettings(
        ignore_case=_coerce_bool(data.get("ignore_case", True), True),
        run_after_probe=_coerce_bool(data.get("run_after_probe", False), False),
        colors=_colors_from_dict(data.get("colors")),
        patterns=patterns,
    )


def dataclass_disabled(pattern: SherlockPattern) -> SherlockPattern:
    """Return a copy of *pattern* with enabled=False (built-ins are frozen)."""
    return SherlockPattern(
        key=pattern.key,
        category=pattern.category,
        label=pattern.label,
        pattern=pattern.pattern,
        severity=pattern.severity,
        enabled=False,
        builtin=pattern.builtin,
    )
